package com.better.rntingrrd.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    private String phoneno;
    private String username;
    private String description;
    private String email;
    private String sex;
    private Integer age;
    private String address;
    private String signature;
    private Integer avlPoints;
    private Integer haspasswd;
    private Integer couponnum;
    private Integer cardnum;
    private Integer hasweixin;
    private Integer hasqq;
    private Integer hassina;
    private String vehicleNo;
    private String uid;
    private String cookie;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String phoneno, String username, String description, String email, String sex, Integer age, String address, String signature, Integer avlPoints, Integer haspasswd, Integer couponnum, Integer cardnum, Integer hasweixin, Integer hasqq, Integer hassina, String vehicleNo, String uid, String cookie) {
        this.id = id;
        this.phoneno = phoneno;
        this.username = username;
        this.description = description;
        this.email = email;
        this.sex = sex;
        this.age = age;
        this.address = address;
        this.signature = signature;
        this.avlPoints = avlPoints;
        this.haspasswd = haspasswd;
        this.couponnum = couponnum;
        this.cardnum = cardnum;
        this.hasweixin = hasweixin;
        this.hasqq = hasqq;
        this.hassina = hassina;
        this.vehicleNo = vehicleNo;
        this.uid = uid;
        this.cookie = cookie;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPhoneno() {
        return phoneno;
    }

    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public Integer getAvlPoints() {
        return avlPoints;
    }

    public void setAvlPoints(Integer avlPoints) {
        this.avlPoints = avlPoints;
    }

    public Integer getHaspasswd() {
        return haspasswd;
    }

    public void setHaspasswd(Integer haspasswd) {
        this.haspasswd = haspasswd;
    }

    public Integer getCouponnum() {
        return couponnum;
    }

    public void setCouponnum(Integer couponnum) {
        this.couponnum = couponnum;
    }

    public Integer getCardnum() {
        return cardnum;
    }

    public void setCardnum(Integer cardnum) {
        this.cardnum = cardnum;
    }

    public Integer getHasweixin() {
        return hasweixin;
    }

    public void setHasweixin(Integer hasweixin) {
        this.hasweixin = hasweixin;
    }

    public Integer getHasqq() {
        return hasqq;
    }

    public void setHasqq(Integer hasqq) {
        this.hasqq = hasqq;
    }

    public Integer getHassina() {
        return hassina;
    }

    public void setHassina(Integer hassina) {
        this.hassina = hassina;
    }

    public String getVehicleNo() {
        return vehicleNo;
    }

    public void setVehicleNo(String vehicleNo) {
        this.vehicleNo = vehicleNo;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getCookie() {
        return cookie;
    }

    public void setCookie(String cookie) {
        this.cookie = cookie;
    }

}
